apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: sanjayaram/myproject:v1
        ports:
        - containerPort: 5000
