apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      # containers:
      # - name: myproject
      #   image: sanjayaram/myproject:v9-20260121-195443
      #   ports:
      #   - containerPort: 5000
      containers:
      - name: myproject
        image: sanjayaram/myproject:v9-20260121-195443
        ports:
        - containerPort: 5000
