apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myproject-ingress
spec:
  rules:
  - host: sj.project
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myproject-service
            port:
              number: 80
